# Generated by Django 5.2.7 on 2025-10-04 05:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('minutos_incluidos', models.IntegerField()),
                ('datos_incluidos_mb', models.IntegerField()),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clientes', models.ManyToManyField(blank=True, related_name='planes', to='clientes.cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
