# Generated by Django 5.2.7 on 2025-10-04 15:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='clientes',
        ),
        migrations.CreateModel(
            name='PlanCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_cliente', to='clientes.cliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_cliente', to='planes.plan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
