# Generated by Django 5.2.7 on 2025-10-04 15:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_remove_plan_clientes_plancliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('minutos_usados', models.IntegerField(default=0)),
                ('datos_usados_mb', models.IntegerField(default=0)),
                ('sms_usados', models.IntegerField(default=0)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('plan_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='planes.plancliente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
