# Generated by Django 5.2.7 on 2025-10-05 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_consumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumo',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='plancliente',
            name='activo',
        ),
        migrations.AddField(
            model_name='consumo',
            name='estado_consumo',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='consumo',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumo',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2025, 10, 5)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plancliente',
            name='celular_asociado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='plancliente',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plancliente',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado')], default='activo', max_length=20),
        ),
    ]
